"""Regenerates the results table and the Findings section in README.md,
between the <!-- RESULTS:START/END --> and <!-- FINDINGS:START/END -->
markers, from data/summary.csv and data/runs.csv. Standalone: depends on
pandas only, does not import the private simulation package.

The unnecessary-dispatch columns are computed as a true rate (mean over
seeds) from data/runs.csv, not from data/summary.csv's median statistic --
median is the wrong aggregate for a rate that isn't 0% or 100%, and using it
here previously hid the decision layer's own small residual (see
docs/PROVENANCE.md and the H3 correction in docs/RESEARCH_HYPOTHESES.md).

Usage: python build_readme_table.py
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

RESULTS_START = "<!-- RESULTS:START -->"
RESULTS_END = "<!-- RESULTS:END -->"
FINDINGS_START = "<!-- FINDINGS:START -->"
FINDINGS_END = "<!-- FINDINGS:END -->"


def _fmt_window(row: pd.Series) -> str:
    n = row["pre_escalation_window_min_n"]
    med = row["pre_escalation_window_min_median"]
    if pd.isna(med):
        return "—"
    if pd.notna(n) and int(n) < int(row["n_seeds"]):
        return f"{med:.0f} (n={int(n)}/{int(row['n_seeds'])})"
    return f"{med:.0f}"


def _fmt_f1(v) -> str:
    return "n/a" if pd.isna(v) else f"{v:.2f}"


def _fmt_pct(v) -> str:
    return "n/a" if pd.isna(v) else f"{v * 100:.0f}%"


def _dispatch_rates(runs: pd.DataFrame) -> pd.DataFrame:
    """True rate (mean over seeds) per (domain, scenario), for both arms."""
    g = runs.groupby(["domain", "scenario"])
    return g.agg(
        conv_unnecessary_dispatch_rate=("conv_unnecessary_dispatch", "mean"),
        layer_unnecessary_dispatch_rate=("layer_unnecessary_dispatch", "mean"),
    ).reset_index()


def build_table(summary: pd.DataFrame, runs: pd.DataFrame) -> str:
    rates = _dispatch_rates(runs)
    df = summary.merge(rates, on=["domain", "scenario"], how="left")
    df = df.sort_values(
        ["domain", "pre_escalation_window_min_median"],
        ascending=[True, False],
        na_position="last",
    )
    lines = [
        "| Domain | Scenario | Pre-escalation window (min, median) | Layer escalation F1 | Conv. escalation F1 | Layer unnecessary dispatch | Conv. unnecessary dispatch |",
        "|---|---|---|---|---|---|---|",
    ]
    for _, row in df.iterrows():
        lines.append(
            "| {domain} | {scenario} | {window} | {layer_f1} | {conv_f1} | {layer_dispatch} | {conv_dispatch} |".format(
                domain=row["domain"],
                scenario=row["scenario"],
                window=_fmt_window(row),
                layer_f1=_fmt_f1(row["layer_esc_f1_median"]),
                conv_f1=_fmt_f1(row["conv_esc_f1_median"]),
                layer_dispatch=_fmt_pct(row["layer_unnecessary_dispatch_rate"]),
                conv_dispatch=_fmt_pct(row["conv_unnecessary_dispatch_rate"]),
            )
        )
    lines.append("")
    lines.append(
        f"*{len(df)} scenarios, {int(df['n_seeds'].iloc[0])} seeds each, "
        f"`duration=600 min`, sorted by domain then by window descending. "
        f"Generated by `build_readme_table.py` from `data/summary.csv` "
        f"(window, F1) and `data/runs.csv` (unnecessary-dispatch rates) — "
        f"not typed by hand. \"n/a\" = no persistent fault was present, so "
        f"escalation F1 is undefined by construction; a window shown with "
        f"`n=` is conditioned on the subset of seeds in which the "
        f"conventional arm escalated at all.*"
    )
    return "\n".join(lines)


def _comparator_config(df: pd.DataFrame, sw, pm, pn, ed) -> pd.DataFrame:
    return df[
        (df["smoothing_window"] == sw) & (df["persistence_m"] == pm)
        & (df["persistence_n"] == pn) & (df["escalation_delay_min"] == ed)
    ]


def build_findings(summary: pd.DataFrame, runs: pd.DataFrame, comparator: pd.DataFrame) -> str:
    nonnull = summary.dropna(subset=["pre_escalation_window_min_median"])
    n_defined = len(nonnull)
    n_total = len(summary)
    win_min = nonnull["pre_escalation_window_min_median"].min()
    win_max = nonnull["pre_escalation_window_min_median"].max()

    sc = runs[runs["gt_self_clearing"] == True]  # noqa: E712
    n_sc = len(sc)
    conv_sc = int(sc["conv_unnecessary_dispatch"].sum())
    layer_sc = int(sc["layer_unnecessary_dispatch"].sum())

    default = _comparator_config(comparator, 5, 3, 5, 8)
    degenerate = _comparator_config(comparator, 1, 1, 1, 0)
    default_window = default["pre_escalation_window_min"].median()
    degenerate_window = degenerate["pre_escalation_window_min"].median()
    default_conv_fpr = default["conv_esc_fpr"].median()
    degenerate_conv_fpr = degenerate["conv_esc_fpr"].median()
    default_conv_sc = default[default["gt_self_clearing"] == True]  # noqa: E712
    degenerate_conv_sc = degenerate[degenerate["gt_self_clearing"] == True]  # noqa: E712
    default_conv_dispatch = default_conv_sc["conv_unnecessary_dispatch"].mean()
    degenerate_conv_dispatch = degenerate_conv_sc["conv_unnecessary_dispatch"].mean()
    layer_fpr_overall = comparator["layer_esc_fpr"].median()
    layer_dispatch_sc = comparator[comparator["gt_self_clearing"] == True]  # noqa: E712
    layer_dispatch_rate = layer_dispatch_sc["layer_unnecessary_dispatch"].mean()

    conv_never = runs.groupby(["domain", "scenario"])["conv_escalated"].mean()
    conv_never = conv_never[conv_never == 0]
    never_parts = []
    for (dom, scen) in conv_never.index:
        d = runs[(runs["domain"] == dom) & (runs["scenario"] == scen)]
        layer_n = int(d["layer_unnecessary_dispatch"].sum())
        layer_total = len(d)
        never_parts.append(
            f"`{scen}` is the only scenario in which the conventional arm never "
            f"escalates, in any of the {layer_total} seeds — its pre-escalation "
            f"window is undefined for every seed as a result. The decision layer "
            f"nonetheless escalated unnecessarily in {layer_n} of {layer_total} "
            f"seeds, part of the residual above."
        )

    bullets = [
        f"Across the {n_sc} self-clearing runs (three scenarios x "
        f"{n_sc // 3} seeds), the conventional arm escalated unnecessarily "
        f"in {conv_sc} ({conv_sc / n_sc:.0%}); the decision layer did so in "
        f"{layer_sc} ({layer_sc / n_sc:.0%}) — a residual, not zero, and the "
        f"single most operationally relevant result in this study.",
        f"The pre-escalation window is not a fixed detection-speed advantage: "
        f"a comparator sweep (`data/sensitivity_comparator.csv`) shows it "
        f"trading against precision. At the default comparator, pooled "
        f"median window {default_window:.0f} min, conventional escalation "
        f"FPR {default_conv_fpr:.0%}, conventional unnecessary dispatch "
        f"{default_conv_dispatch:.0%}. At a DEGENERATE comparator (a "
        f"perfect, instantaneous, unsmoothed threshold monitor), window "
        f"{degenerate_window:.0f} min, conventional escalation FPR "
        f"{degenerate_conv_fpr:.0%}, conventional unnecessary dispatch "
        f"{degenerate_conv_dispatch:.0%} — it buys the apparent lead with "
        f"false alarms. The decision layer's own escalation FPR "
        f"({layer_fpr_overall:.0%}) and unnecessary-dispatch rate "
        f"({layer_dispatch_rate:.0%}) do not move under any comparator "
        f"tuning. See `figures/fig10_latency_precision_tradeoff.png`.",
        f"A positive pre-escalation window at the default comparator is "
        f"observed in {n_defined} of {n_total} scenarios, with medians "
        f"ranging from {win_min:.0f} to {win_max:.0f} minutes — but this "
        f"range describes the default comparator's behaviour as much as the "
        f"decision layer's; see the trade-off finding above.",
    ] + never_parts

    return "\n".join(f"- {b}" for b in bullets[:4])


def _replace_block(text: str, start: str, end: str, body: str) -> str:
    if start not in text or end not in text:
        raise SystemExit(f"README.md is missing {start} / {end} markers")
    pre, rest = text.split(start, 1)
    _, post = rest.split(end, 1)
    return f"{pre}{start}\n{body}\n{end}{post}"


def main() -> int:
    readme_path = Path("README.md")
    summary = pd.read_csv("data/summary.csv")
    runs = pd.read_csv("data/runs.csv")
    comparator = pd.read_csv("data/sensitivity_comparator.csv")

    text = readme_path.read_text()
    text = _replace_block(text, RESULTS_START, RESULTS_END, build_table(summary, runs))
    text = _replace_block(text, FINDINGS_START, FINDINGS_END, build_findings(summary, runs, comparator))
    readme_path.write_text(text)
    print(
        f"README.md results table and findings regenerated from data/summary.csv "
        f"({len(summary)} rows), data/runs.csv ({len(runs)} rows) and "
        f"data/sensitivity_comparator.csv ({len(comparator)} rows)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
